In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import sys
import os
import numpy as np
pd.set_option('display.max_columns', 1000);

Dashboard Objectives

    Provide interactive visualizations for key patient health indicators.
    Assist nursing students in understanding clinical assessments from OASIS and county level data (Census & SDOH).

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import holoviews as hv
from bokeh.palettes import Category10
import scipy.cluster.hierarchy as sch

from bokeh.plotting import figure

In [3]:
import panel as pn
pn.extension()

In [4]:
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

counties["features"][0]

{'type': 'Feature',
 'properties': {'GEO_ID': '0500000US01001',
  'STATE': '01',
  'COUNTY': '001',
  'NAME': 'Autauga',
  'LSAD': 'County',
  'CENSUSAREA': 594.436},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-86.496774, 32.344437],
    [-86.717897, 32.402814],
    [-86.814912, 32.340803],
    [-86.890581, 32.502974],
    [-86.917595, 32.664169],
    [-86.71339, 32.661732],
    [-86.714219, 32.705694],
    [-86.413116, 32.707386],
    [-86.411172, 32.409937],
    [-86.496774, 32.344437]]]},
 'id': '01001'}

In [5]:
df = pd.read_csv('data/dashboardData_ICDSections_v2.csv', low_memory=False)

In [6]:
df

,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,Unknown_Race_Ethnicity,White,ByDiscipline,DaysBetweenVisits,Days_Cared_For,READMISSION,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code,Other_Diagnosis_Code_1_ICD_10_C_M,Other_Diagnosis_Code_2_ICD_10_C_M,Other_Diagnosis_Code_3_ICD_10_C_M,Other_Diagnosis_Code_4_ICD_10_C_M,Other_Diagnosis_Code_5_ICD_10_C_M,Weight_in_pounds,Height_in_inches,is_diabetes,is_heart_failure,is_hypertension,is_renal_failure,BMI,BMI_Category,COUNTY_NAME,POP_COU,HOU_COU,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,COUNTYFIPS,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ANY,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_CIVIL_NONINST_POP_POV,ACS_TOT_CIVIL_POP_POV,ACS_TOT_POP_POV,ICD_Section,ICD_Range
0,GGGGGGG99DXUNNS,2017-11-29,4BGLS,20709,77,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PT,NaN,56,0,679120,I69.354,I69.311,F03.90,I10.,H35.3290,Z91.81,NaN,NaN,0,0,0,0,0,Underweight,Travis,1290188.0,562488.0,1224251.0,94.89,65937.0,5.11,48453,32.074345,22.720897,18.759759,15.975069,10.125310,1.126621,73.554724,43.738517,32.210448,21.982241,5.364069,77.367655,88.875172,6.101690,82.169241,9.295000,0.120241,88.995310,3.084621,3.860310,6.885931,2.473000,0.005034,85.658207,2.725345,5.117103,90.312759,5.603414,68.051034,0.605414,5.587552,26.428103,31.441345,8.488448,20.070172,28.869621,18.399828,6.166552,14.115345,59.224138,9.056379,25.322103,47.800931,17.476414,15.557483,6.956862,2.961000,8.280103,7.701241,6.646034,4.280931,11.512966,3.100828,10.822793,73.126034,12.605586,5.032621,10.705379,19.303103,14.320379,11.069241,2.068966,14.276517,9.661000,9.426172,4223.255172,3299.406897,4225.820690,"{'Diseases of the eye and adnexa', 'Diseases o...","{'F01-F99', 'Z00-Z99', 'I00-I99', 'H00-H59'}"
1,GGGGGGG99GWNzUW,2017-02-08,1AHKS,696175,74,Female,0.0,0.0,1.0,0.0,0.0,NaN,0.0,RN,NaN,314,0,747199,I25.10,I25.83,I50.42,M12.89,M54.30,R26.89,146.0,65.0,0,0,0,0,25,Overweight,Harris,4731145.0,1842683.0,4677507.0,98.87,53638.0,1.13,48201,20.002284,25.887536,11.996951,22.838174,19.185522,1.939011,57.886619,31.882239,36.757860,28.122410,12.653121,68.342320,85.252104,6.312617,78.048615,14.276799,0.141951,85.394164,2.052950,7.455809,12.283121,2.412104,0.018714,74.575108,3.227824,7.685683,86.899218,12.036313,59.834092,0.734829,8.129937,33.536888,38.805908,10.236151,24.519155,26.830728,21.947275,7.247464,21.881277,93.839029,12.250612,28.372572,34.331007,24.776376,24.694119,13.773768,6.257833,9.230647,14.404757,7.291655,4.506214,14.438022,5.353849,14.852644,62.705198,16.818489,6.254451,11.774038,17.916232,18.082023,14.639892,0.612113,17.751070,13.141808,9.128750,4165.090827,3054.184353,4167.452338,"{'not elsewhere classified', 'signs and abnorm...","{'I00-I99', 'M00-M99', 'R00-R99'}"
2,GGGGGGG99NWze9G,2017-10-16,1CHKT,83192,75,Male,0.0,0.0,0.0,0.0,0.0,NaN,1.0,RN,NaN,56,0,679372,L03.114,I11.0,I50.9,J44.9,I25.10,F17.210,197.0,66.0,0,0,0,0,32,Obese-Class1,Bowie,92893.0,39536.0,57646.0,62.06,35247.0,37.94,48037,13.153846,33.281923,7.370769,35.667308,10.525000,0.661154,53.806923,20.079231,41.513846,38.408077,0.795769,54.897692,71.698077,7.666923,61.746154,13.377692,0.351154,72.049615,3.468846,20.300000,24.481154,1.093462,0.120000,63.823462,4.888077,16.515769,72.741538,11.768846,33.311538,0.359231,14.919231,39.696923,26.125769,26.372308,43.655769,30.853077,32.633846,12.482308,21.652692,111.923077,13.427692,31.598077,30.037692,24.936923,25.905000,12.053462,7.215769,11.689615,12.323077,8.606538,3.174615,16.306538,5.153846,15.103462,61.638077,18.105000,2.220769,3.846154,19.703462,11.421923,22.495000,3.846154,6.445769,15.411538,14.380769,3375.500000,2529.307692,3376.115385,"{'Diseases of the circulatory system', 'Mental...","{'F01-F99', 'I00-I99', 'J00-J99', 'L00-L99'}"
3,GGGGGGG99NeDX99,2017-03-01,4BGKS,1472419,72,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,397,0,747517,E11.22,I13.2,I50.9,N18.6,I48.2,D63.1,NaN,NaN,0,0,0,0,0,Underweight,Harris,4731145.0,1842683.0,4677507.0,98.87,53638.0,1.13,48201,20.002284,25.887536,11.996951,22.838174,19.185522,1.939011,57.886619,31.882239,36.757860,28.122410,12.653121,68.342320,85.252104,6.312617,78.048615,14.276799,0.141951,85.394164,2.052950,7.455809,12.283121,2.412104,0.018714,74.575108,3.227824,7.685683,86.899218,12.036313,59.834092,0.734829,8.129937,33.536888,38.805908,10.236151,24.519155,26.830728,21.947275,7.247464,21.881277,93.839029,12.250612,28.372572,34.331007,24.776376,24.694119,13.773768,6.257833,9.230647,14.404757,7.291655,4.506214,14.438022,5.353849,14.852644,62.705198,16.818489,6.254451,11.774038,17.916232,18.082023,14.639892,0.612113,17.751070,13.141808,9.128750,4165.090827,3054.184353,4167.452338,"{'nutritional and metabolic diseases', 'Diseas...","{'D50-D89', 'E00-E89', 'N00-N99', 'I00-I99'}"
4,GGGGGGG99S9eeNG,2017-04-06,3BGKS,3396341,74,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,837,0,747909,E11.9,I10.,M10.9,E78.5,E03.9,M19.012,NaN,NaN,0,0,0,0,0,Underweight,Jim Wells,38891.0,16156.0,19413.0,49.92,19478.0,50.08,48249,11.921818,27.913636,4.406364,34.315455,21.446364,0.795455,44.239091,17.598182,32.280909,50.120000,7.776364,47.620000,66.845455,13.958182,48.866364,10.177273,0.288182,67.133636,1.754545,23.666364,31.111818,2.650000,0.000000,63.172727,13.531818,13.952727,61.383636,9.549091,29.725455,0.713636,18.581818,33.286364,47.649091,15.755455,27.504545,19.467273,31.725455,8.910909,22.246364,191.909091,14.171818,30.250000,27.308182,28.270909,32.624545,17.028182,8.758182,9.075455,17.190909,11.914545,2.070000,16.760909,3.427273,18.450000,57.556364,20.564545,20.255455,0.000000,11.363636,21.660000,11.477273,0.000000,16.250000,10.021818,12.255455,3662.454545,2639.727273,3662.454545,"{'Diseases of the circulatory system', 'Diseas...","{'E00-E89', 'M00-M99', 'I00-I99'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444767,GGGGGGXzezDW9WN,2017-09-14,2AGKS,372944,66,Male,0.0,0.0,0.0,1.0,0.0,NaN,0.0,RN,NaN,40,0,677949,Z91.81,I10.,R73.03,K70.30,M62.81,NaN,NaN,NaN,0,0,0,0,0,Underweight,Dallas,2613539.0,1038656.0,2598426.0,99.42,15113.0,0.58,48113,20.988509,24.817189,12.637981,22.061491,19.339860,1.534286,58.443525,33.383649,36.730280,27.867314,9.999193,68.165373,84.583385,5.061848,77.982236,13.287640,0.162034,84.745295,2.575031,7.577065,12.369208,6.133929,0.024783,75.187655,3.187360,6.559503,86.710947,11.674224,59.402516,0.650342,8.581366,34.603882,40.321879,10.455031,23.291460,28.347873,21.821537,7.568851,20.811817,102.635093,12.766584,29.797236,35.208773,21.916988,19.324953,10.620823,4.563339,8.240140,11.187516,5.930932,4.398804,11.923835,5.332578,15.425699,65.013183,13.918214,5.883696,9.716553,15.984161,15.772283,12.433401,0.359363,14.423183,10.034922,7.618354,4024.355590,2969.970497,4025.928571,"{'not elsewhere classified', 'signs and abnorm...","{'K00-K95', 'M00-M99', 'R00-R99', 'Z00-Z99', '..."
444768,GGGGGGXzezWGS9W,2017-08-22,NaN,303296,35,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,55,0,677874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,Underweight,Galveston,350682.0,156191.0,336429.0,95.94,14253.0,4.06,48167,20.483039,32.591961,10.837941,24.593137,10.512647,1.558039,63.914314,30.930686,39.571373,28.518431,2.765392,69.815686,87.449412,4.611765,82.149706,13.574216,0.298333,87.747647,1.892843,6.432843,9.379020,2.123725,0.082745,78.392353,3.136667,7.348529,87.467255,8.878039,64.563137,0.635882,9.173137,29.431275,37.105784,12.857745,26.506863,26.584412,27.902843,10.116667,16.831176,62.872549,10.147157,25.128039,46.414804,17.328922,20.880000,10.722941,4.060392,7.508627,11.163627,4.949216,3.694020,11.166176,3.870588,12.067843,71.593824,11.486176,4.224314,9.499902,12.590686,13.846471,11.553824,0.980392,9.385392,9.711569,7.017451,3241.784314,2448.303922,3245.901961,{'Unknown'},{'Unknown'}
444769,GGGGGGXzezXDeDW,2017-12-01,1CGKU,639032,61,Male,0.0,0.0,1.0,0.0,0.0,NaN,0.0,RN,NaN,0,0,747092,S71.101A,S81.801D,I10.,B18.2,K70.30,I73.9,140.0,68.0,0,0,0,0,22,Normal weight,Dallas,2613539.0,1038656.0,2598426.0,99.42,15113.0,0.58,48113,20.988509,24.817189,12.637981,22.061491,19.339860,1.534286,58.443525,33.383649,36.730280,27.867314,9.999193,68.165373,84.583385,5.061848,77.982236,13.287640,0.162034,84.745295,2.575031,7.577065,12.369208,6.133929,0.024783,75.187655,3.187360,6.559503,86.710947,11.674224,59.402516,0.650342,8.581366,34.603882,40.321879,10.455031,23.291460,28.347873,21.821537,7.568851,20.811817,102.635093,12.766584,29.797236,35.208773,21.916988,19.324953,10.620823,4.563339,8.240140,11.187516,5.930932,4.398804,11.923835,5.332578,15.425699,65.013183,13.918214,5.883696,9.716553,15.984161,15.772283,12.433401,0.359363,14.423183,10.034922,7.618354,4024.355590,2969.970497,4025.928571,"{'Injury', 'Certain infectious and parasitic d...","{'A00-B99', 'S00-T88', 'I00-I99', 'K00-K95'}"
444770,GGGGGGXzzGe9XWN,2017-05-06,1BHKV,376749,66,Male,0.0,0.0,0.0,1.0,0.0,NaN,0.0,RN,NaN,55,0,679522,S21.102D,I10.,Z85.028,NaN,NaN,NaN,175.0,73.0,0,0,0,0,24,Normal weight,El Paso,865657.0,317894.0,830826.0,95.98,34831.0,4.02,48141,14.964521,31.078777,7.088936,23.227074,23.108511,1.812500,53.132660,26.251755,43.925106,29.290745,24.270532,60.546277,80.876436,5.884840,74.297660,16.754734,0.158138,81.034681,2.948670,11.240904,15.484894,1.536489,0.007979,67.868777,2.977181,7.637979,83.073883,13.922447,55.598351,0.738032,12.805745,36.121330,50.884521,8.389734,30.619734,23.578191,27.837713,8.995053,24.909468,142.569149,16.209521,30.811809,20.171383,32.275532,32.848245,21.728936,11.547447,9.945638,22.284787,7.939309,4.297926,18.836436,6.865213,20.067394,51.200319,21.334521,8.853830,7.861755,14.174787,22.245638,20.189415,1.595745,23.420585,15.349096,8.230479,4310.936170,3111.734043,4370.893617,"{'Diseases of the circulatory system', 'poison...","{'S00-T88', 'Z00-Z99', 'I00-I99'}"
444771,GGGGGGXzzNUeN9X,2017-12-22,1CGPV,297214,64,Female,0.0,0.0,0.0,1.0,0.0,NaN,0.0,RN,NaN,0,0,457954,A41.9,N39.0,I49.9,I10.,I50.9,E11.9,246.0,60.0,0,0,0,0,49,Obese-Class3,Harris,4731145.0,1842683.0,4677507.0,98.87,53638.0,1.13,48201,20.002284,25.887536,11.996951,22.838174,19.185522,1.939011,57.886619,31.882239,36.757860,28.122410,12.653121,68.342320,85.252104,6.312617,78.048615,14.276799,0.141951,85.394164,2.052950,7.455809,12.283121,2.412104,0.018714,74.575108,3.227824,7.685683,86.899218,12.036313,59.834092,0.734829,8.129937,33.536888,38.805908,10.236151,24.519155,26.830728,21.947275,7.247464,21.881277,93.839029,12.250612,28.372572,34.331007,24.776376,24.694119,13.773768,6.257833,9.230647,14.404757,7.291655,4.506214,14.438022,5.353849,14.852644,62.705198,16.818489,6.254451,11.774038,17.916232,18.082023,14.639892,0.612113,17.751070,13.141808,9.128750,4165.090827,3054.184353,4167.452338,"{'nutritional and metabolic diseases', 'Diseas...","{'I00-I99', 'N00-N99', 'E00-E89', 'A00-B99'}"

In [7]:
df['COUNTYFIPS'] = df['COUNTYFIPS'].astype(int)

In [8]:
df.columns.tolist()

['Beneficiary_ID',
 'Assessment_Effective_Date',
 'Submitted_HIPPS_Code',
 'Facility_Internal_ID',
 'Age',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'ByDiscipline',
 'DaysBetweenVisits',
 'Days_Cared_For',
 'READMISSION',
 'Agency_Medicare_Number',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Weight_in_pounds',
 'Height_in_inches',
 'is_diabetes',
 'is_heart_failure',
 'is_hypertension',
 'is_renal_failure',
 'BMI',
 'BMI_Category',
 'COUNTY_NAME',
 'POP_COU',
 'HOU_COU',
 'POP_URB',
 'POPPCT_URB',
 'POP_RUR',
 'POPPCT_RUR',
 'COUNTYFIPS',
 'ACS_PCT_BACHELOR_DGR',
 'ACS_PCT_COLLEGE_ASSOCIATE_DGR',
 'ACS_PCT_GRADUATE_DGR',
 'ACS_PCT_HS_GRADUATE',
 'ACS_PCT_LT_HS',
 'ACS_PCT_NO_WORK_NO_SCHL_16_19',
 'ACS_PCT_POSTHS_ED',
 'ACS_PCT_VET_BACHELOR',
 'ACS_PCT_VET_COLLEGE',
 'ACS_PCT_VET_HS',
 'ACS_PCT_HH_LIMIT_ENGLISH',
 'ACS_PCT_HH_BROADBAND',
 'ACS_PCT_HH_BROADBAND_ANY',
 'ACS_PCT_HH_BROADBAND_ONLY',
 'ACS_PCT_HH_CELLULAR',
 'ACS_PCT_HH_CELLULAR_ONLY',
 'ACS_PCT_HH_DIAL_INTERNET_ONLY',
 'ACS_PCT_HH_INTERNET',
 'ACS_PCT_HH_INTERNET_NO_SUBS',
 'ACS_PCT_HH_NO_COMP_DEV',
 'ACS_PCT_HH_NO_INTERNET',
 'ACS_PCT_HH_OTHER_COMP',
 'ACS_PCT_HH_OTHER_COMP_ONLY',
 'ACS_PCT_HH_PC',
 'ACS_PCT_HH_PC_ONLY',
 'ACS_PCT_HH_SAT_INTERNET',
 'ACS_PCT_HH_SMARTPHONE',
 'ACS_PCT_HH_SMARTPHONE_ONLY',
 'ACS_PCT_HH_TABLET',
 'ACS_PCT_HH_TABLET_ONLY',
 'ACS_PCT_CHILDREN_GRANDPARENT',
 'ACS_PCT_CHILD_1FAM',
 'ACS_PCT_GRANDP_NO_RESPS',
 'ACS_PCT_GRANDP_RESPS_NO_P',
 'ACS_PCT_GRANDP_RESPS_P',
 'ACS_PCT_HH_1PERS',
 'ACS_PCT_HH_ABOVE65',
 'ACS_PCT_HH_ALONE_ABOVE65',
 'ACS_PCT_HH_KID_1PRNT',
 'ACS_TOT_GRANDCHILDREN_GP',
 'ACS_PCT_HEALTH_INC_138_199',
 'ACS_PCT_HEALTH_INC_200_399',
 'ACS_PCT_HEALTH_INC_ABOVE400',
 'ACS_PCT_HEALTH_INC_BELOW137',
 'ACS_PCT_HH_1FAM_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP_BLW_POV',
 'ACS_PCT_HH_NO_FD_STMP_BLW_POV',
 'ACS_PCT_HH_PUB_ASSIST',
 'ACS_PCT_INC50',
 'ACS_PCT_INC50_ABOVE65',
 'ACS_PCT_NONVET_POV_18_64',
 'ACS_PCT_PERSON_INC_100_124',
 'ACS_PCT_PERSON_INC_125_199',
 'ACS_PCT_PERSON_INC_ABOVE200',
 'ACS_PCT_PERSON_INC_BELOW99',
 'ACS_PCT_POV_AIAN',
 'ACS_PCT_POV_ASIAN',
 'ACS_PCT_POV_BLACK',
 'ACS_PCT_POV_HISPANIC',
 'ACS_PCT_POV_MULTI',
 'ACS_PCT_POV_NHPI',
 'ACS_PCT_POV_OTHER',
 'ACS_PCT_POV_WHITE',
 'ACS_PCT_VET_POV_18_64',
 'ACS_TOT_CIVIL_NONINST_POP_POV',
 'ACS_TOT_CIVIL_POP_POV',
 'ACS_TOT_POP_POV',
 'ICD_Section',
 'ICD_Range']

In [10]:
from shapely.geometry import shape
import geopandas as gpd

In [11]:
features = counties["features"]
geometry = [shape(feature['geometry']) for feature in features]
names = [feature['properties']['NAME'] for feature in features]
fips = [feature['id'] for feature in features]
states = [feature['properties']['STATE'] for feature in features]

geo_df = gpd.GeoDataFrame({
    'County': names,
    'Fips': fips,
    'geometry': geometry,
    'State': states
})
geo_df

,County,Fips,geometry,State
0,Autauga,01001,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028...",01
1,Blount,01009,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406...",01
2,Chambers,01017,"POLYGON ((-85.18413 32.87052, -85.12342 32.772...",01
3,Chilton,01021,"POLYGON ((-86.51734 33.02057, -86.51596 32.929...",01
4,Colbert,01033,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878...",01
...,...,...,...,...
3216,Accomack,51001,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ...",51
3217,Bland,51021,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430...",51
3218,Buchanan,51027,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212...",51
3219,Charlotte,51037,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912...",51
3220,Chesterfield,51041,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183...",51

In [12]:
geo_df.set_crs('EPSG:4326', allow_override=True, inplace=True)
#source: https://public-rma.fpac.usda.gov/ReportShare//Extranet/SOB/Listings/StateAbbr2014.pdf
data = {
    "State_Abbreviation": [
        "AK", "AL", "AR", "AS", "AS", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "FM", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", 
        "MA", "MD", "ME", "MH", "MI", "MN", "MO", "MP", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", 
        "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UM", "UT", "VA", "VI", "VI", "VT", "WA", "WI", "WV", "WY", "ZZ"
    ],
    "State_name": [
        "ALASKA", "ALABAMA", "ARKANSAS", "AMERICAN SAMOA", "ALL STATES", "ARIZONA", "CALIFORNIA", "COLORADO", "CONNECTICUT", "D. OF COLUMBIA",
        "DELAWARE", "FLORIDA", "FS OF MICRONESI", "GEORGIA", "GUAM", "HAWAII", "IOWA", "IDAHO", "ILLINOIS", "INDIANA", "KANSAS", "KENTUCKY",
        "LOUISIANA", "MASSACHUSETTS", "MARYLAND", "MAINE", "MARSHALL ISLAND", "MICHIGAN", "MINNESOTA", "MISSOURI", "NORTHERN MARIAN", 
        "MISSISSIPPI", "MONTANA", "NORTH CAROLINA", "NORTH DAKOTA", "NEBRASKA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEVADA", 
        "NEW YORK", "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "PUERTO RICO", "PUERTO RICO", "PALAU", "RHODE ISLAND", "SOUTH CAROLINA", 
        "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "U.S. MINOR OUTL", "UTAH", "VIRGINIA", "VIRGIN ISLANDS", "VIRGIN ISLANDS", "VERMONT", "WASHINGTON", 
        "WISCONSIN", "WEST VIRGINIA", "WYOMING", "FOREIGN"
    ],
    "Code": [
        "02", "01", "05", "60", "98", "04", "06", "08", "09", "11", "10", "12", "64", "13", "66", "15", "19", "16", "17", "18", "20", "21", "22", 
        "25", "24", "23", "68", "26", "27", "29", "69", "28", "30", "37", "38", "31", "33", "34", "35", "32", "36", "39", "40", "41", "42", "72", 
        "43", "70", "44", "45", "46", "47", "48", "74", "49", "51", "78", "52", "50", "53", "55", "54", "56", "99"
    ]
}

codes = pd.DataFrame(data)
codes

   State_Abbreviation      State_name Code
0                  AK          ALASKA   02
1                  AL         ALABAMA   01
2                  AR        ARKANSAS   05
3                  AS  AMERICAN SAMOA   60
4                  AS      ALL STATES   98
..                ...             ...  ...
59                 WA      WASHINGTON   53
60                 WI       WISCONSIN   55
61                 WV   WEST VIRGINIA   54
62                 WY         WYOMING   56
63                 ZZ         FOREIGN   99

[64 rows x 3 columns]

In [13]:
merged_data = pd.merge(geo_df, codes, right_on=['Code'], left_on=['State'])
merged_data

,County,Fips,geometry,State,State_Abbreviation,State_name,Code
0,Autauga,01001,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028...",01,AL,ALABAMA,01
1,Blount,01009,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406...",01,AL,ALABAMA,01
2,Chambers,01017,"POLYGON ((-85.18413 32.87052, -85.12342 32.772...",01,AL,ALABAMA,01
3,Chilton,01021,"POLYGON ((-86.51734 33.02057, -86.51596 32.929...",01,AL,ALABAMA,01
4,Colbert,01033,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878...",01,AL,ALABAMA,01
...,...,...,...,...,...,...,...
3216,Accomack,51001,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ...",51,VA,VIRGINIA,51
3217,Bland,51021,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430...",51,VA,VIRGINIA,51
3218,Buchanan,51027,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212...",51,VA,VIRGINIA,51
3219,Charlotte,51037,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912...",51,VA,VIRGINIA,51
3220,Chesterfield,51041,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183...",51,VA,VIRGINIA,51

In [14]:
merged_data = merged_data[merged_data['State_Abbreviation'] == 'TX' ]
merged_data = merged_data.drop(['State', 'State_Abbreviation', 'State_name', 'Code'], axis=1)
merged_data

         County   Fips                                           geometry
525   Ochiltree  48357  POLYGON ((-100.93606 36.4996, -100.91851 36.49...
526      Oldham  48359  POLYGON ((-103.04238 35.18316, -103.0425 35.21...
527      Parker  48367  POLYGON ((-97.54418 32.99418, -97.55037 32.580...
528       Rains  48379  POLYGON ((-95.66539 32.96043, -95.63502 32.720...
529     Randall  48381  POLYGON ((-102.16884 34.74742, -102.16747 35.1...
...         ...    ...                                                ...
3089  Jefferson  48245  POLYGON ((-94.35416 29.56146, -94.35798 29.887...
3090    Kaufman  48257  POLYGON ((-96.52999 32.54528, -96.52312 32.545...
3118     Panola  48365  POLYGON ((-94.51143 31.97398, -94.59998 31.973...
3119    Haskell  48207  POLYGON ((-99.47244 33.39902, -99.47126 32.957...
3134     Potter  48375  POLYGON ((-101.62294 35.18312, -102.16747 35.1...

[254 rows x 3 columns]

In [15]:
merged_data['Fips'] = merged_data['Fips'].astype(int)

In [16]:
merged_data = pd.merge(
    merged_data,
    df,
    left_on=['County', 'Fips'],
    right_on=['COUNTY_NAME', 'COUNTYFIPS']
)
merged_data = merged_data.drop(['COUNTY_NAME', 'COUNTYFIPS'], axis=1)

merged_data

,County,Fips,geometry,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,Unknown_Race_Ethnicity,White,ByDiscipline,DaysBetweenVisits,Days_Cared_For,READMISSION,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code,Other_Diagnosis_Code_1_ICD_10_C_M,Other_Diagnosis_Code_2_ICD_10_C_M,Other_Diagnosis_Code_3_ICD_10_C_M,Other_Diagnosis_Code_4_ICD_10_C_M,Other_Diagnosis_Code_5_ICD_10_C_M,Weight_in_pounds,Height_in_inches,is_diabetes,is_heart_failure,is_hypertension,is_renal_failure,BMI,BMI_Category,POP_COU,HOU_COU,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ANY,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_CIVIL_NONINST_POP_POV,ACS_TOT_CIVIL_POP_POV,ACS_TOT_POP_POV,ICD_Section,ICD_Range
0,Ochiltree,48357,"POLYGON ((-100.93606 36.4996, -100.91851 36.49...",GGGGGGGS9zSDSSS,2017-10-10,3BFKS,9645,76,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,296,0,457640,M71.112,Z48.00,M54.31,I73.9,I50.9,J44.9,NaN,NaN,0,0,0,0,0,Underweight,10015.0,4332.0,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,82.073333,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,12.360000,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,2246.000000,3272.000000,"{'Diseases of the circulatory system', 'Factor...","{'Z00-Z99', 'I00-I99', 'M00-M99', 'J00-J99'}"
1,Ochiltree,48357,"POLYGON ((-100.93606 36.4996, -100.91851 36.49...",GGGGGGGWGeeDNDG,2017-11-15,1AGPS,9645,91,Male,0.0,0.0,0.0,0.0,0.0,NaN,1.0,RN,NaN,0,0,457640,D64.9,Z51.89,R53.1,E11.8,E16.2,R42.,114.0,68.0,1,0,0,0,18,Underweight,10015.0,4332.0,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,82.073333,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,12.360000,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,2246.000000,3272.000000,"{'not elsewhere classified', 'Endocrine', 'nut...","{'D50-D89', 'Z00-Z99', 'E00-E89', 'R00-R99'}"
2,Ochiltree,48357,"POLYGON ((-100.93606 36.4996, -100.91851 36.49...",GGGGGGUWGSeWSXD,2017-05-29,NaN,9645,68,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,15,0,457640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,Underweight,10015.0,4332.0,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,82.073333,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,12.360000,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,2246.000000,3272.000000,{'Unknown'},{'Unknown'}
3,Ochiltree,48357,"POLYGON ((-100.93606 36.4996, -100.91851 36.49...",GGGGGGGWNXXSNeD,2017-08-19,1BGPS,9645,86,Male,0.0,0.0,0.0,0.0,0.0,NaN,1.0,RN,NaN,17,0,457640,K92.2,R53.1,Z51.89,D64.9,I10.,G20.,153.0,70.0,0,0,0,0,22,Normal weight,10015.0,4332.0,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,82.073333,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,12.360000,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,2246.000000,3272.000000,"{'not elsewhere classified', 'Diseases of the ...","{'K00-K95', 'R00-R99', 'Z00-Z99', 'G00-G99', '..."
4,Ochiltree,48357,"POLYGON ((-100.93606 36.4996, -100.91851 36.49...",GGGGGGGUDUezNNe,2017-10-06,3AGKS,9645,87,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,235,0,457640,N18.4,R56.9,E87.1,Z46.6,R55.,N39.0,NaN,NaN,0,0,0,0,0,Underweight,10015.0,4332.0,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,82.073333,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,12.360000,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,2246.000000,3272.000000,"{'not elsewhere classified', 'Endocrine', 'nut...","{'Z00-Z99', 'E00-E89', 'N00-N99', 'R00-R99'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444767,Potter,48375,"POLYGON ((-101.62294 35.18312, -102.16747 35.1...",GGGGGGXeDeSDSSe,2017-12-14,NaN,9659,51,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,236,0,457590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,Underweight,118525.0,48692.0,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,75.188571,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,15.259429,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3180.685714,2262.542857,3184.428571,{'Unknown'},{'Unknown'}
444768,Potter,48375,"POLYGON ((-101.62294 35.18312, -102.16747 35.1...",GGGGGGXzGSNSXWD,2017-01-20,2BHMS,9644,70,Female,0.0,0.0,0.0,0.0,0.0,NaN,1.0,RN,NaN,13,0,459482,A04.7,J44.9,M62.50,N39.0,B96.4,C50.919,87.0,0.0,1,0,0,1,0,Underweight,118525.0,48692.0,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,75.188571,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,15.259429,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3180.685714,2262.542857,3184.428571,"{'Neoplasms', 'Diseases of the genitourinary s...","{'N00-N99', 'M00-M99', 'A00-B99', 'J00-J99', '..."
444769,Potter,48375,"POLYGON ((-101.62294 35.18312, -102.16747 35.1...",GGGGGGXzGzDUeSW,2017-04-11,3CHKS,366724,70,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,356,0,677943,I69.354,I73.9,I25.10,I10.,E78.5,Z91.81,NaN,NaN,0,0,0,0,0,Underweight,118525.0,48692.0,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,75.188571,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,15.259429,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3180.685714,2262.542857,3184.428571,"{'Diseases of the circulatory system', 'Factor...","{'Z00-Z99', 'I00-I99', 'E00-E89'}"
444770,Potter,48375,"POLYGON ((-101.62294 35.18312, -102.16747 35.1...",GGGGGGXzSSeGDUW,2017-04-18,NaN,9528,39,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,302,0,677447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,Underweight,118525.0,48692.0,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,75.188571,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,15.259429,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3180.685714,2262.542857,3184.428571,{'Unknown'},{'Unknown'}
444771,Potter,48375,"POLYGON ((-101.62294 35.18312, -102.16747 35.1...",GGGGGGXzSeDDD9z,2017-06-12,1AFKS,366724,70,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RN,NaN,176,0,677943,C50.811,Z90.11,D64.81,I10.,Z79.811,Z85.3,NaN,NaN,0,0,0,0,0,Underweight,118525.0,48692.0,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,75.188571,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,15.259429,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3180.685714,2262.542857,3184.428571,"{'Diseases of the circulatory system', 'Neopla...","{'Z00-Z99', 'I00-I99', 'D50-D89', 'C00-D49'}"

In [17]:
merged_data.columns.tolist()

['County',
 'Fips',
 'geometry',
 'Beneficiary_ID',
 'Assessment_Effective_Date',
 'Submitted_HIPPS_Code',
 'Facility_Internal_ID',
 'Age',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'ByDiscipline',
 'DaysBetweenVisits',
 'Days_Cared_For',
 'READMISSION',
 'Agency_Medicare_Number',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Weight_in_pounds',
 'Height_in_inches',
 'is_diabetes',
 'is_heart_failure',
 'is_hypertension',
 'is_renal_failure',
 'BMI',
 'BMI_Category',
 'POP_COU',
 'HOU_COU',
 'POP_URB',
 'POPPCT_URB',
 'POP_RUR',
 'POPPCT_RUR',
 'ACS_PCT_BACHELOR_DGR',
 'ACS_PCT_COLLEGE_ASSOCIATE_DGR',
 'ACS_PCT_GRADUATE_DGR',
 'ACS_PCT_HS_GRADUATE',
 'ACS_PCT_LT_HS',
 'ACS_PCT_NO_WORK_NO_SCHL_16_19',
 'ACS_PCT_POSTHS_ED',
 'ACS_PCT_VET_BACHELOR',
 'ACS_PCT_VET_COLLEGE',
 'ACS_PCT_VET_HS',
 'ACS_PCT_HH_LIMIT_ENGLISH',
 'ACS_PCT_HH_BROADBAND',
 'ACS_PCT_HH_BROADBAND_ANY',
 'ACS_PCT_HH_BROADBAND_ONLY',
 'ACS_PCT_HH_CELLULAR',
 'ACS_PCT_HH_CELLULAR_ONLY',
 'ACS_PCT_HH_DIAL_INTERNET_ONLY',
 'ACS_PCT_HH_INTERNET',
 'ACS_PCT_HH_INTERNET_NO_SUBS',
 'ACS_PCT_HH_NO_COMP_DEV',
 'ACS_PCT_HH_NO_INTERNET',
 'ACS_PCT_HH_OTHER_COMP',
 'ACS_PCT_HH_OTHER_COMP_ONLY',
 'ACS_PCT_HH_PC',
 'ACS_PCT_HH_PC_ONLY',
 'ACS_PCT_HH_SAT_INTERNET',
 'ACS_PCT_HH_SMARTPHONE',
 'ACS_PCT_HH_SMARTPHONE_ONLY',
 'ACS_PCT_HH_TABLET',
 'ACS_PCT_HH_TABLET_ONLY',
 'ACS_PCT_CHILDREN_GRANDPARENT',
 'ACS_PCT_CHILD_1FAM',
 'ACS_PCT_GRANDP_NO_RESPS',
 'ACS_PCT_GRANDP_RESPS_NO_P',
 'ACS_PCT_GRANDP_RESPS_P',
 'ACS_PCT_HH_1PERS',
 'ACS_PCT_HH_ABOVE65',
 'ACS_PCT_HH_ALONE_ABOVE65',
 'ACS_PCT_HH_KID_1PRNT',
 'ACS_TOT_GRANDCHILDREN_GP',
 'ACS_PCT_HEALTH_INC_138_199',
 'ACS_PCT_HEALTH_INC_200_399',
 'ACS_PCT_HEALTH_INC_ABOVE400',
 'ACS_PCT_HEALTH_INC_BELOW137',
 'ACS_PCT_HH_1FAM_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP_BLW_POV',
 'ACS_PCT_HH_NO_FD_STMP_BLW_POV',
 'ACS_PCT_HH_PUB_ASSIST',
 'ACS_PCT_INC50',
 'ACS_PCT_INC50_ABOVE65',
 'ACS_PCT_NONVET_POV_18_64',
 'ACS_PCT_PERSON_INC_100_124',
 'ACS_PCT_PERSON_INC_125_199',
 'ACS_PCT_PERSON_INC_ABOVE200',
 'ACS_PCT_PERSON_INC_BELOW99',
 'ACS_PCT_POV_AIAN',
 'ACS_PCT_POV_ASIAN',
 'ACS_PCT_POV_BLACK',
 'ACS_PCT_POV_HISPANIC',
 'ACS_PCT_POV_MULTI',
 'ACS_PCT_POV_NHPI',
 'ACS_PCT_POV_OTHER',
 'ACS_PCT_POV_WHITE',
 'ACS_PCT_VET_POV_18_64',
 'ACS_TOT_CIVIL_NONINST_POP_POV',
 'ACS_TOT_CIVIL_POP_POV',
 'ACS_TOT_POP_POV',
 'ICD_Section',
 'ICD_Range']

In [18]:
merged_data.to_csv('data/texasCountySummariesOASIS.csv', index=False)

In [28]:
merged_data_copy1 = merged_data.copy()

In [29]:
merged_data_copy2 =merged_data_copy1[['Beneficiary_ID', 'County', 'READMISSION'
 'Fips',
 'geometry',
 'Submitted_HIPPS_Code',
 'Facility_Internal_ID',
 'Age',
 'Gender',
 'American_Indian_or_Alaska_Native',
 'Asian',
 'Black_or_African_American',
 'Hispanic_or_Latino',
 'Native_Hawiian_or_Pacific_Islander',
 'Unknown_Race_Ethnicity',
 'White',
 'ByDiscipline',
 'DaysBetweenVisits',
 'Days_Cared_For',
 'Agency_Medicare_Number',
 'Primary_Diagnosis_ICD_10_C_M_Code',
 'Other_Diagnosis_Code_1_ICD_10_C_M',
 'Other_Diagnosis_Code_2_ICD_10_C_M',
 'Other_Diagnosis_Code_3_ICD_10_C_M',
 'Other_Diagnosis_Code_4_ICD_10_C_M',
 'Other_Diagnosis_Code_5_ICD_10_C_M',
 'Weight_in_pounds',
 'Height_in_inches',
 'is_diabetes',
 'is_heart_failure',
 'is_hypertension',
 'is_renal_failure',
 'BMI',
 'BMI_Category',
 'POP_COU',
 'HOU_COU',
 'POP_URB',
 'POPPCT_URB',
 'POP_RUR',
 'POPPCT_RUR',
 'ICD_Section',
 'ICD_Range']]

KeyError: "['READMISSIONFips'] not in index"

In [ ]:
merged_data_copy2

In [27]:
# Grouping the data
grouped_df = merged_data_copy2.groupby(['County', 'Fips']).agg(
    BENE_ID_unique=('Beneficiary_ID', 'nunique'),
    FACINTID_unique=('Facility_Internal_ID', 'nunique'),
    SBMHPSCD_unique=('Submitted_HIPPS_Code', 'nunique'),
    Age_mean=('Age', 'mean'),
    Gender_counts=('Gender', lambda x: x.value_counts().to_dict()),
    American_Indian_or_Alaska_Native_unique=('American_Indian_or_Alaska_Native', 'nunique'),
    Black_or_African_American_unique=('Black_or_African_American', 'nunique'),
    Hispanic_or_Latino_unique=('Hispanic_or_Latino', 'nunique'),
    Native_Hawiian_or_Pacific_Islander_unique=('Native_Hawiian_or_Pacific_Islander', 'nunique'),
    Unknown_Race_Ethnicity_unique=('American_Indian_or_Alaska_Native', 'nunique'),    
    White_unique=('White', 'nunique'),    
    ByDiscipline_counts=('ByDiscipline', lambda x: x.value_counts().to_dict()),
    M0010_counts=('Agency_Medicare_Number', lambda x: x.value_counts().to_dict()),
    DaysBetweenVisits_mean=('DaysBetweenVisits', 'mean'),
    Days_Cared_For_mean=('Days_Cared_For', 'mean'),
    BMI_Category_counts=('BMI_Category', lambda x: x.value_counts().to_dict()),
    Diabetic_patient_count=('is_diabetes', lambda x: (x == 1).sum()),
    HeartFailure_patient_count=('is_heart_failure', lambda x: (x == 1).sum()),
    Hypertension_patient_count=('is_hypertension', lambda x: (x == 1).sum()),
    RenalFailure_patient_count=('is_renal_failure', lambda x: (x == 1).sum()),
    Readmission_1_count=('READMISSION', lambda x: (x == 1).sum()),
    Readmission_0_count=('READMISSION', lambda x: (x == 0).sum()),
    geometry=('geometry', 'first'),
    POP_COU=('POP_COU', 'first'),
    HOU_COU=('HOU_COU', 'first'),
    POP_URB=('POP_URB', 'first'),
    POPPCT_URB=('POPPCT_URB', 'first'),
    POP_RUR=('POP_RUR', 'first'),
    POPPCT_RUR=('POPPCT_RUR', 'first'),
    ICD_Section=('ICD_Section', lambda x: ','.join(sorted(set(','.join(x).split(','))))),
    ICD_Range=('ICD_Range', lambda x: ','.join(sorted(set(','.join(x).split(',')))))
).reset_index()
grouped_df

KeyError: "Column(s) ['READMISSION'] do not exist"

In [21]:
grouped_df.columns

Index(['County', 'Fips', 'BENE_ID_unique', 'FACINTID_unique',
       'HHA_AGNCY_ID_unique', 'SBMHPSCD_unique', 'Age_mean', 'Gender_counts',
       'Race_counts', 'ByDiscipline_counts', 'M0010_counts',
       'DaysBetweenVisits_mean', 'Days_Cared_For_mean', 'BMI_Category_counts',
       'Diabetic_patient_count', 'HeartFailure_patient_count',
       'Hypertension_patient_count', 'Readmission_1_count',
       'Readmission_0_count', 'geometry', 'POP_COU', 'HOU_COU', 'POP_URB',
       'POPPCT_URB', 'POP_RUR', 'POPPCT_RUR', 'ICD_Section', 'ICD_Range'],
      dtype='object')

In [22]:
# Filter Texas counties
texas_counties_geojson = {
    "type": "FeatureCollection",
    "features": [feature for feature in counties['features'] if feature['properties']['STATE'] == '48']
}

In [23]:
grouped_df.to_csv('streamlit/streamlit_df.csv', index=False)

In [24]:
# Grouping the data
grouped_df = merged_data_copy1.groupby(['County', 'Fips']).agg(
    BENE_ID_unique=('BENE_ID', 'nunique'),
    FACINTID_unique=('FACINTID', 'nunique'),
    HHA_AGNCY_ID_unique=('HHA_AGNCY_ID', 'nunique'),
    SBMHPSCD_unique=('SBMHPSCD', 'nunique'),
    Diabetic_patient_count=('Diabetic_patient', lambda x: (x == 1).sum()),
    HeartFailure_patient_count=('HeartFailure_patient', lambda x: (x == 1).sum()),
    Hypertension_patient_count=('Hypertension_patient', lambda x: (x == 1).sum()),
    
    Readmission_1_count=('Readmission', lambda x: (x == 1).sum()),
    Readmission_0_count=('Readmission', lambda x: (x == 0).sum()),
    geometry=('geometry', 'first'),
    POP_COU=('POP_COU', 'first'),
    HOU_COU=('HOU_COU', 'first'),
    POP_URB=('POP_URB', 'first'),
    POPPCT_URB=('POPPCT_URB', 'first'),
    POP_RUR=('POP_RUR', 'first'),
    POPPCT_RUR=('POPPCT_RUR', 'first'),
).reset_index()
grouped_df

,County,Fips,BENE_ID_unique,FACINTID_unique,HHA_AGNCY_ID_unique,SBMHPSCD_unique,Diabetic_patient_count,HeartFailure_patient_count,Hypertension_patient_count,Readmission_1_count,Readmission_0_count,geometry,POP_COU,HOU_COU,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR
0,Anderson,48001,338,27,27,108,407.0,151.0,330.0,109.0,298.0,"POLYGON ((-95.42851 32.08447, -95.44675 31.843...",57922.0,20131.0,18615.0,32.14,39307.0,67.86
1,Andrews,48003,53,11,11,36,66.0,17.0,53.0,20.0,46.0,"POLYGON ((-102.28705 32.08699, -102.79909 32.0...",18610.0,7020.0,15201.0,81.68,3409.0,18.32
2,Angelina,48005,569,27,27,163,657.0,179.0,536.0,152.0,505.0,"POLYGON ((-94.32662 31.22475, -94.12963 31.099...",86395.0,36480.0,41551.0,48.09,44844.0,51.91
3,Aransas,48007,131,24,24,66,143.0,30.0,111.0,34.0,109.0,"MULTIPOLYGON (((-96.85345 28.06134, -96.92905 ...",23830.0,15500.0,18212.0,76.42,5618.0,23.58
4,Archer,48009,62,15,15,42,69.0,25.0,51.0,16.0,53.0,"POLYGON ((-98.95309 33.83400, -98.74236 33.834...",8560.0,3865.0,1082.0,12.64,7478.0,87.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Wood,48499,361,42,42,119,418.0,133.0,341.0,93.0,325.0,"POLYGON ((-95.15341 32.57012, -95.16752 32.543...",44843.0,22129.0,5699.0,12.71,39144.0,87.29
244,Yoakum,48501,26,4,4,17,32.0,12.0,28.0,11.0,21.0,"POLYGON ((-102.59502 32.95883, -103.06466 32.9...",7694.0,3009.0,0.0,0.00,7694.0,100.00
245,Young,48503,161,11,11,78,190.0,70.0,113.0,50.0,140.0,"POLYGON ((-98.95087 32.95692, -98.95394 33.397...",17867.0,8539.0,8585.0,48.05,9282.0,51.95
246,Zapata,48505,143,17,17,48,163.0,14.0,138.0,42.0,121.0,"POLYGON ((-98.95423 26.78569, -99.01111 26.675...",13889.0,6159.0,10942.0,78.78,2947.0,21.22
247,Zavala,48507,114,13,13,46,132.0,39.0,117.0,32.0,100.0,"POLYGON ((-99.41388 29.09134, -99.40902 28.640...",9670.0,3920.0,6709.0,69.38,2961.0,30.62

In [25]:
sdoh =merged_data_copy1[['County',
 'Fips',
 'ACS_PCT_BACHELOR_DGR',
 'ACS_PCT_COLLEGE_ASSOCIATE_DGR',
 'ACS_PCT_GRADUATE_DGR',
 'ACS_PCT_HS_GRADUATE',
 'ACS_PCT_LT_HS',
 'ACS_PCT_NO_WORK_NO_SCHL_16_19',
 'ACS_PCT_POSTHS_ED',
 'ACS_PCT_VET_BACHELOR',
 'ACS_PCT_VET_COLLEGE',
 'ACS_PCT_VET_HS',
 'ACS_PCT_HH_LIMIT_ENGLISH',
 'ACS_PCT_HH_BROADBAND',
 'ACS_PCT_HH_BROADBAND_ANY',
 'ACS_PCT_HH_BROADBAND_ONLY',
 'ACS_PCT_HH_CELLULAR',
 'ACS_PCT_HH_CELLULAR_ONLY',
 'ACS_PCT_HH_DIAL_INTERNET_ONLY',
 'ACS_PCT_HH_INTERNET',
 'ACS_PCT_HH_INTERNET_NO_SUBS',
 'ACS_PCT_HH_NO_COMP_DEV',
 'ACS_PCT_HH_NO_INTERNET',
 'ACS_PCT_HH_OTHER_COMP',
 'ACS_PCT_HH_OTHER_COMP_ONLY',
 'ACS_PCT_HH_PC',
 'ACS_PCT_HH_PC_ONLY',
 'ACS_PCT_HH_SAT_INTERNET',
 'ACS_PCT_HH_SMARTPHONE',
 'ACS_PCT_HH_SMARTPHONE_ONLY',
 'ACS_PCT_HH_TABLET',
 'ACS_PCT_HH_TABLET_ONLY',
 'ACS_PCT_CHILDREN_GRANDPARENT',
 'ACS_PCT_CHILD_1FAM',
 'ACS_PCT_GRANDP_NO_RESPS',
 'ACS_PCT_GRANDP_RESPS_NO_P',
 'ACS_PCT_GRANDP_RESPS_P',
 'ACS_PCT_HH_1PERS',
 'ACS_PCT_HH_ABOVE65',
 'ACS_PCT_HH_ALONE_ABOVE65',
 'ACS_PCT_HH_KID_1PRNT',
 'ACS_TOT_GRANDCHILDREN_GP',
 'ACS_PCT_HEALTH_INC_138_199',
 'ACS_PCT_HEALTH_INC_200_399',
 'ACS_PCT_HEALTH_INC_ABOVE400',
 'ACS_PCT_HEALTH_INC_BELOW137',
 'ACS_PCT_HH_1FAM_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP',
 'ACS_PCT_HH_FOOD_STMP_BLW_POV',
 'ACS_PCT_HH_NO_FD_STMP_BLW_POV',
 'ACS_PCT_HH_PUB_ASSIST',
 'ACS_PCT_INC50',
 'ACS_PCT_INC50_ABOVE65',
 'ACS_PCT_NONVET_POV_18_64',
 'ACS_PCT_PERSON_INC_100_124',
 'ACS_PCT_PERSON_INC_125_199',
 'ACS_PCT_PERSON_INC_ABOVE200',
 'ACS_PCT_PERSON_INC_BELOW99',
 'ACS_PCT_POV_AIAN',
 'ACS_PCT_POV_ASIAN',
 'ACS_PCT_POV_BLACK',
 'ACS_PCT_POV_HISPANIC',
 'ACS_PCT_POV_MULTI',
 'ACS_PCT_POV_NHPI',
 'ACS_PCT_POV_OTHER',
 'ACS_PCT_POV_WHITE',
 'ACS_PCT_VET_POV_18_64',
 'ACS_TOT_CIVIL_NONINST_POP_POV',
 'ACS_TOT_CIVIL_POP_POV',
 'ACS_TOT_POP_POV',
]]

In [26]:
df = grouped_df.merge(sdoh, on=['County', 'Fips']).drop_duplicates()
df

,County,Fips,BENE_ID_unique,FACINTID_unique,HHA_AGNCY_ID_unique,SBMHPSCD_unique,Diabetic_patient_count,HeartFailure_patient_count,Hypertension_patient_count,Readmission_1_count,Readmission_0_count,geometry,POP_COU,HOU_COU,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ANY,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_CIVIL_NONINST_POP_POV,ACS_TOT_CIVIL_POP_POV,ACS_TOT_POP_POV
0,Anderson,48001,338,27,27,108,407.0,151.0,330.0,109.0,298.0,"POLYGON ((-95.42851 32.08447, -95.44675 31.843...",57922.0,20131.0,18615.0,32.14,39307.0,67.86,7.841667,32.505833,4.401667,38.857500,16.396667,0.484167,44.747500,21.754168,43.486668,34.760000,1.988333,45.035830,67.546670,12.244166,52.398335,13.515000,0.416667,67.963330,2.157500,11.767500,21.545834,6.010000,0.0000,61.189167,4.223333,16.269167,72.36000,12.733334,46.878334,0.625000,10.084167,30.835000,37.776670,20.465834,33.424168,23.509167,29.446667,10.115833,16.695833,103.250000,19.629168,32.141666,21.355000,26.874166,27.555000,10.730833,4.674167,6.685834,12.410833,4.845833,2.404167,18.850000,4.595833,21.844166,53.496666,20.064167,18.616667,9.615000,22.032500,21.848333,22.510834,0.0,10.224167,9.229167,2.745000,3700.1667,2778.0833,3700.1667
407,Andrews,48003,53,11,11,36,66.0,17.0,53.0,20.0,46.0,"POLYGON ((-102.28705 32.08699, -102.79909 32.0...",18610.0,7020.0,15201.0,81.68,3409.0,18.32,11.447500,27.912500,4.192500,33.095000,23.350000,0.000000,43.550000,28.932500,31.685000,39.382500,8.120000,63.585000,89.395000,6.152500,80.537500,18.565000,0.127500,89.522500,0.722500,6.565000,9.755000,1.482500,0.2375,70.922500,3.365000,8.900000,85.82500,12.707500,63.812500,0.185000,8.790000,27.960000,47.802500,19.100000,33.097500,17.877500,22.322500,7.277500,16.767500,102.500000,9.615000,35.280000,36.475000,18.632500,11.412500,7.582500,3.515000,6.657500,7.582500,7.362500,3.050000,9.477500,5.740000,12.320000,71.752500,10.190000,0.000000,0.000000,0.000000,16.182500,2.860000,0.0,6.445000,3.332500,4.860000,4529.5000,3137.0000,4529.5000
473,Angelina,48005,569,27,27,163,657.0,179.0,536.0,152.0,505.0,"POLYGON ((-94.32662 31.22475, -94.12963 31.099...",86395.0,36480.0,41551.0,48.09,44844.0,51.91,12.648571,33.956192,5.838095,30.977620,16.579048,4.775238,52.443810,18.338572,41.577618,40.083332,2.256667,63.463333,84.765720,8.862381,74.194280,14.499524,0.292857,85.059525,1.530000,10.047143,13.410953,2.098571,0.0000,70.207146,5.489524,6.886667,80.57333,10.967143,59.636192,1.046191,12.400476,35.436670,45.828094,21.942858,32.228573,23.362858,31.778095,9.943334,23.423810,120.857140,15.026667,31.463810,25.890953,27.619524,42.563330,19.355238,9.342381,6.512857,19.982857,6.592381,3.434286,16.405237,7.108572,18.352858,57.371430,17.166191,10.395715,2.931429,14.470000,29.201430,12.452857,0.0,11.297143,14.445238,10.269524,4015.3809,2988.5240,4018.1904
1130,Aransas,48007,131,24,24,66,143.0,30.0,111.0,34.0,109.0,"MULTIPOLYGON (((-96.85345 28.06134, -96.92905 ...",23830.0,15500.0,18212.0,76.42,5618.0,23.58,15.248181,33.189090,7.039091,25.700909,9.731818,0.000000,55.476364,21.560000,38.647274,30.702726,1.713636,51.195454,76.467270,5.117273,68.071815,15.670909,0.160000,76.627270,2.386364,8.068182,11.895454,1.278182,0.0000,69.135450,6.648182,11.594545,74.89455,9.741818,50.612730,0.229091,10.631818,42.742725,44.347270,7.774546,20.606363,29.731817,39.053635,14.689091,10.640909,61.272728,13.456364,22.982727,29.630000,24.838182,38.998180,12.763637,7.559091,9.303637,12.990909,10.503636,3.516364,19.363636,4.257273,14.531818,52.615456,19.510000,1.623636,10.028182,9.090909,29.560910,20.259090,0.0,20.050000,15.585455,17.344545,2164.1820,1726.6364,2164.1820
1273,Archer,48009,62,15,15,42,69.0,25.0,51.0,16.0,53.0,"POLYGON ((-98.95309 33.83400, -98.74236 33.834...",8560.0,3865.0,1082.0,12.64,7478.0,87.36,14.163333,31.650000,7.956666,36.646667,9.586667,1.096667,53.770000,14.960000,41.280000,43.760000,1.540000,54.710000,77.463330,5.166666,71.596664,14.933333,0.000000,77.463330,6.536667,11.606667,16.000000,1.890000,0.0000,70.083336,5.333334,10.076667,81.55666,13.366667,48.496666,0.070000,4.116667,21.976667,31.110000,14.000000,54.890000,24.596666,36.423332,13.950000,13.596666,25.000000,11.816667,29.786667,41.603333,16.793333,28.986666,8.153334,4.706666,7.903333,9.933333,4.910000,2.790000,10.313334,2.636667,14.310000,71.386665,11.663333,0.000000,0.000000,9.523334,7.193333,5.126666,0.0,0.000000,12.103333,3.940000,2899.3333,2265.3333,2899.3333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119119,Wood,48499,361,42,42,119,418.0,133.0,341.0,93.0,325.0,"POLYGON ((-95.15341 32.57012, -95.16752 32.543...",44843.0,22129.0,5699.0,12.71,39144.0,87.29,11.927500,33.395832,6.443333,33.071667,15.161667,1.633333,51.767500,19.207500,40.080833,40.711666,0.715000,47.636665,79.667500,5.922500,71.000000,19.941668,0.518333,80.184166,2.459167,11.231667,17.357500,1.598333,0.0450,70.050000,5.040000,15.366667,79.77167,11.416667,53.040000,0.935000,10.711667,27.737500,36.592500,42.918335,20.487500,26.626667,47.159170,14.749167,13.320833,80.250000,13.156667,35.531666,32.997500,18.316668,30.841667,10.709167,5.221667,7.937500,11.184167,4.331666,3.250000,11.868333,4.501666,14.834167,68.526665,12.137500,0.000000,2.020000,22.715834,16.135000,24.215834,0.0,14.785000,10.627500,12.403334,3613.9167,2901.2500,3613.9167
119537,Yoakum,48501,26,4,4,17,32.0,12.0,28.0,11.0,21.0,"POLYGON ((-102.59502 32.95883, -103.06466 32.9...",7694.0,3009.0,0.0,0.00,7694.0,100.00,11.130000,29.590000,1.980000,25.205000,32.095000,0.000000,42.705000,6.250000,66.320000,27.430000,14.125000,60.845000,82.165000,1.790000,79.455000,16.650000,0.000000,82.165000,0.515000,8.955000,17.320000,0.085000,0.0000,57.435000,0.430000,9.195000,88.69500,18.245000,62.940000,0.860000,10.895000,24.045000,5.000000,46.430000,48.570000,18.370000,28.155000,8.550000,14.680000,174.500000,15.045000,31.760000,33.315000,19.885000,33.225000,10.220000,4.580000,6.245000,10.390000,4.980000,2.625000,8.345000,1.900000,20.710000,65.070000,12.320000,0.000000,0.000000,0.000000,18.420000,28.175000,0.0,65.255000,4.435000,0.000000,4306.0000,2887.5000,4306.0000
119569,Young,48503,161,11,11,78,190.0,70.0,113.0,50.0,140.0,"POLYGON ((-98.95087 32.95692, -98.95394 33.397...",17867.0,8539.0,8585.0,48.05,9282.0,51.95,15.674000,30.740000,7.480000,30.966000,15.144000,0.000000,53.888000,34.192000,38.944000,26.860000,5.676000,51.050000,79.860000,3.492000,75.578000,18.412000,0.450000,80.310000,3.588000,10.254000,16.102000,1.768000,0.0000,63.738000,3.892000,12.042000,83.76400,22.196000,42.692000,0.770000,4.040000,28.288000,40.000000,40.000000,0.000000,26.400000,35.420000,11.406000,16.078000,27.400000,10.052000,33.538000,36.338000,20.074000,27.972000,8.998000,4.390000,9.900000,9.578000,5.328000,3.482000,13.076000,5.116000,12.106000,69.894000,12.888000,0.000000,20.000000,5.964000,20.070000,7.142000,0.0,32.678000,10.894000,4.590000,3527.4000,2666.6000,3530.2000
119759,Zapata,48505,143,17,17,48,163.0,14.0,138.0,42.0,121.0,"POLYGON ((-98.95423 26.78569, -99.01111 26.675...",13889.0,6159.0,10942.0,78.78,2947.0,21.22,11.126667,22.873333,1.083333,30.160000,34.751667,0.000000,35.083332,11.053333,34.393333,54.553333,30.295000,51.181667,62.891666,22.856667,38.301666,7.218333,0.000000,62.891666,0.428333,20.100000,36.680000,0.000000,0.0000,45.706665,4.481667,8.993333,74.04667,24.921667,43.023335,0.150000,13.645000,48.273335,50.763332,0.000000,32.570000,27.293333,31.595000,15.331667,32.753334,78.666664,17.538334,27.831667,14.203333,40.430000,23.733334,24.021667,15.036667,14.236667,24.021667,14.911667,2.531667,21.328333,8.213333,20.481667,42.033333,29.276667,0.000000,0.000000,0.000000,29.555000,20.133333,0.0,39.231667,26.091667,0.000000,2341.6667,1575.0000,2341.6667
119922,Zavala,48507,114,13,13,46,132.0,39.0,117.0,32.0,100.0,"POLYGON ((-99.41388 29.09134, -99.40902 28.640...",9670.0,3920.0,6709.0,69.38,2961.0,30.62,5.672500,26.702500,3.967500,33.642500,30.020000,0.000000,36.342500,14.482500,39.522500,45.992500,9.212500,43.125000,61.500000,27.665000,27.835000,11.195000,0.000000,61.500000,6.352500,13.690000,32.147500,0.307500,0.0000,41.582500,4.602500,9.560000,79.38000,35.857500,36.980000,1.672500,22.710000,65.415000,35.462500,11.467500,53.070000,14.712500,35.415000,10.497500,28.812500,176.000000,13.627500,22.467500,12.490000,51.415000,61.387500,30.865000,22.857500,10.517500,31.452500,19.097500,4.167500,28.587500,7.715000,17.032500,34.957500,40.295000,0.000000,0.000000,25.000000,36.837500,15.837500,0.0,8.937500,43.810000,25.000000,2950.2500,2084.2500,2950.2500

In [27]:
print(df['geometry'].dtype)

geometry

In [28]:
topics = {
    'Attainment':['ACS_PCT_BACHELOR_DGR', 'ACS_PCT_COLLEGE_ASSOCIATE_DGR', 'ACS_PCT_GRADUATE_DGR', 'ACS_PCT_HS_GRADUATE', 'ACS_PCT_LT_HS',
                  'ACS_PCT_NO_WORK_NO_SCHL_16_19', 'ACS_PCT_POSTHS_ED', 'ACS_PCT_VET_BACHELOR', 'ACS_PCT_VET_COLLEGE', 'ACS_PCT_VET_HS'],
    'English Fluency':[ 'ACS_PCT_HH_LIMIT_ENGLISH' ],
    'Internet Connectivity'	:['ACS_PCT_HH_BROADBAND', 'ACS_PCT_HH_BROADBAND_ANY', 'ACS_PCT_HH_BROADBAND_ONLY', 'ACS_PCT_HH_CELLULAR', 'ACS_PCT_HH_CELLULAR_ONLY',
                              'ACS_PCT_HH_DIAL_INTERNET_ONLY', 'ACS_PCT_HH_INTERNET', 'ACS_PCT_HH_INTERNET_NO_SUBS', 'ACS_PCT_HH_NO_COMP_DEV', 'ACS_PCT_HH_NO_INTERNET',
                              'ACS_PCT_HH_OTHER_COMP', 'ACS_PCT_HH_OTHER_COMP_ONLY', 'ACS_PCT_HH_PC', 'ACS_PCT_HH_PC_ONLY', 'ACS_PCT_HH_SAT_INTERNET', 'ACS_PCT_HH_SMARTPHONE', 'ACS_PCT_HH_SMARTPHONE_ONLY', 'ACS_PCT_HH_TABLET', 'ACS_PCT_HH_TABLET_ONLY'],
    'Living Conditions'	:['ACS_PCT_CHILDREN_GRANDPARENT', 'ACS_PCT_CHILD_1FAM', 'ACS_PCT_GRANDP_NO_RESPS', 'ACS_PCT_GRANDP_RESPS_NO_P', 'ACS_PCT_GRANDP_RESPS_P', 
                          'ACS_PCT_HH_1PERS', 'ACS_PCT_HH_ABOVE65', 'ACS_PCT_HH_ALONE_ABOVE65', 'ACS_PCT_HH_KID_1PRNT', 'ACS_TOT_GRANDCHILDREN_GP'],
    'Poverty':['ACS_PCT_HEALTH_INC_138_199', 'ACS_PCT_HEALTH_INC_200_399', 'ACS_PCT_HEALTH_INC_ABOVE400', 'ACS_PCT_HEALTH_INC_BELOW137', 'ACS_PCT_HH_1FAM_FOOD_STMP',
                  'ACS_PCT_HH_FOOD_STMP', 'ACS_PCT_HH_FOOD_STMP_BLW_POV', 'ACS_PCT_HH_NO_FD_STMP_BLW_POV', 'ACS_PCT_HH_PUB_ASSIST', 'ACS_PCT_INC50', 'ACS_PCT_INC50_ABOVE65', 
                  'ACS_PCT_NONVET_POV_18_64', 'ACS_PCT_PERSON_INC_100_124', 'ACS_PCT_PERSON_INC_125_199', 'ACS_PCT_PERSON_INC_ABOVE200', 'ACS_PCT_PERSON_INC_BELOW99', 
                  'ACS_PCT_POV_AIAN', 'ACS_PCT_POV_ASIAN', 'ACS_PCT_POV_BLACK', 'ACS_PCT_POV_HISPANIC', 'ACS_PCT_POV_MULTI', 'ACS_PCT_POV_NHPI', 'ACS_PCT_POV_OTHER', 
                  'ACS_PCT_POV_WHITE', 'ACS_PCT_VET_POV_18_64', 'ACS_TOT_CIVIL_NONINST_POP_POV', 'ACS_TOT_CIVIL_POP_POV', 'ACS_TOT_POP_POV'],
}

In [35]:
disparity_results = []

# Iterate through the topics and calculate disparity metrics for each county
for topic, indicators in topics.items():
    for indicator in indicators:
        # Calculate the overall average of the indicator
        avg_value = df[indicator].mean()

        for index, row in df.iterrows():
            # Calculate Absolute Index of Disparity (AID) for the county
            aid = abs(row[indicator] - avg_value)
            
            # Calculate Relative Index of Disparity (RID) for the county
            rid = aid / avg_value
            
            # Calculate Population-Weighted Index of Disparity (PWID) for the county
            pwid = abs(row[indicator] - avg_value) * row['POP_COU'] / df['POP_COU'].sum()
            
            # Calculate Population Attributable Proportion (PAP) for the county (urban vs rural)
            urban_disparity = abs(row[indicator] - avg_value) * row['POP_COU'] if row['POPPCT_URB'] > 0.5 else 0
            rural_disparity = abs(row[indicator] - avg_value) * row['POP_COU'] if row['POPPCT_RUR'] > 0.5 else 0
            total_disparity = abs(row[indicator] - avg_value) * row['POP_COU']
            pap = urban_disparity / total_disparity if total_disparity > 0 else 0
            
            # Store the results for each county
            disparity_results.append({
                'County': row['County'],
                'Topic': topic,
                'Indicator': indicator,
                'AbsoluteIndexDisparity': aid,
                'RelativeIndexDisparity': rid,
                'PopulationWeightedIndexDisparity': pwid,
                'PopulationAttributableProportion': pap
            })
disparity_df = pd.DataFrame(disparity_results)
disparity_df

,County,Topic,Indicator,AbsoluteIndexDisparity,RelativeIndexDisparity,PopulationWeightedIndexDisparity,PopulationAttributableProportion
0,Anderson,Attainment,ACS_PCT_BACHELOR_DGR,5.715634,0.421591,0.011360,1.0
1,Andrews,Attainment,ACS_PCT_BACHELOR_DGR,2.109801,0.155621,0.001347,1.0
2,Angelina,Attainment,ACS_PCT_BACHELOR_DGR,0.908730,0.067029,0.002694,1.0
3,Aransas,Attainment,ACS_PCT_BACHELOR_DGR,1.690880,0.124721,0.001383,1.0
4,Archer,Attainment,ACS_PCT_BACHELOR_DGR,0.606032,0.044702,0.000178,1.0
...,...,...,...,...,...,...,...
16859,Wood,Poverty,ACS_TOT_POP_POV,358.141819,0.110002,0.551103,1.0
16860,Yoakum,Poverty,ACS_TOT_POP_POV,1050.225119,0.322573,0.277279,0.0
16861,Young,Poverty,ACS_TOT_POP_POV,274.425119,0.084289,0.168251,1.0
16862,Zapata,Poverty,ACS_TOT_POP_POV,914.108181,0.280765,0.435664,1.0
16863,Zavala,Poverty,ACS_TOT_POP_POV,305.524881,0.093841,0.101381,1.0

In [36]:
disparity_df['Indicator'] = disparity_df['Indicator'].str.replace('ACS_PCT', '%')
disparity_df['Indicator'] = disparity_df['Indicator'].str.replace('ACS_TOT', 'TOTAL').str.replace('_', ' ')

disparity_df

,County,Topic,Indicator,AbsoluteIndexDisparity,RelativeIndexDisparity,PopulationWeightedIndexDisparity,PopulationAttributableProportion
0,Anderson,Attainment,% BACHELOR DGR,5.715634,0.421591,0.011360,1.0
1,Andrews,Attainment,% BACHELOR DGR,2.109801,0.155621,0.001347,1.0
2,Angelina,Attainment,% BACHELOR DGR,0.908730,0.067029,0.002694,1.0
3,Aransas,Attainment,% BACHELOR DGR,1.690880,0.124721,0.001383,1.0
4,Archer,Attainment,% BACHELOR DGR,0.606032,0.044702,0.000178,1.0
...,...,...,...,...,...,...,...
16859,Wood,Poverty,TOTAL POP POV,358.141819,0.110002,0.551103,1.0
16860,Yoakum,Poverty,TOTAL POP POV,1050.225119,0.322573,0.277279,0.0
16861,Young,Poverty,TOTAL POP POV,274.425119,0.084289,0.168251,1.0
16862,Zapata,Poverty,TOTAL POP POV,914.108181,0.280765,0.435664,1.0
16863,Zavala,Poverty,TOTAL POP POV,305.524881,0.093841,0.101381,1.0

In [38]:
disparity_df['Indicator'].unique()

array(['% BACHELOR DGR', '% COLLEGE ASSOCIATE DGR', '% GRADUATE DGR',
       '% HS GRADUATE', '% LT HS', '% NO WORK NO SCHL 16 19',
       '% POSTHS ED', '% VET BACHELOR', '% VET COLLEGE', '% VET HS',
       '% HH LIMIT ENGLISH', '% HH BROADBAND', '% HH BROADBAND ANY',
       '% HH BROADBAND ONLY', '% HH CELLULAR', '% HH CELLULAR ONLY',
       '% HH DIAL INTERNET ONLY', '% HH INTERNET',
       '% HH INTERNET NO SUBS', '% HH NO COMP DEV', '% HH NO INTERNET',
       '% HH OTHER COMP', '% HH OTHER COMP ONLY', '% HH PC',
       '% HH PC ONLY', '% HH SAT INTERNET', '% HH SMARTPHONE',
       '% HH SMARTPHONE ONLY', '% HH TABLET', '% HH TABLET ONLY',
       '% CHILDREN GRANDPARENT', '% CHILD 1FAM', '% GRANDP NO RESPS',
       '% GRANDP RESPS NO P', '% GRANDP RESPS P', '% HH 1PERS',
       '% HH ABOVE65', '% HH ALONE ABOVE65', '% HH KID 1PRNT',
       'TOTAL GRANDCHILDREN GP', '% HEALTH INC 138 199',
       '% HEALTH INC 200 399', '% HEALTH INC ABOVE400',
       '% HEALTH INC BELOW137', '% HH 1FAM FOOD STMP', '% HH FOOD STMP',
       '% HH FOOD STMP BLW POV', '% HH NO FD STMP BLW POV',
       '% HH PUB ASSIST', '% INC50', '% INC50 ABOVE65',
       '% NONVET POV 18 64', '% PERSON INC 100 124',
       '% PERSON INC 125 199', '% PERSON INC ABOVE200',
       '% PERSON INC BELOW99', '% POV AIAN', '% POV ASIAN', '% POV BLACK',
       '% POV HISPANIC', '% POV MULTI', '% POV NHPI', '% POV OTHER',
       '% POV WHITE', '% VET POV 18 64', 'TOTAL CIVIL NONINST POP POV',
       'TOTAL CIVIL POP POV', 'TOTAL POP POV'], dtype=object)

In [37]:
disparity_df.to_csv('streamlit/streamlit_sdoh.csv', index=False)