In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
pd.set_option('display.max_columns', 1000)

In [2]:
df = pd.read_csv("../texasCountySummariesOASIS.csv")
print(df.columns)

/tmp/ipykernel_551919/1671755169.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../texasCountySummariesOASIS.csv")

Index(['County', 'Fips', 'geometry', 'Beneficiary_ID',
       'Assessment_Effective_Date', 'Submitted_HIPPS_Code',
       'Facility_Internal_ID', 'Age', 'Gender',
       'American_Indian_or_Alaska_Native',
       ...
       'ACS_PCT_POV_BLACK', 'ACS_PCT_POV_HISPANIC', 'ACS_PCT_POV_MULTI',
       'ACS_PCT_POV_NHPI', 'ACS_PCT_POV_OTHER', 'ACS_PCT_POV_WHITE',
       'ACS_PCT_VET_POV_18_64', 'ACS_TOT_POP_POV', 'ICD_Section', 'ICD_Range'],
      dtype='object', length=101)

In [4]:
df

,County,Fips,geometry,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,ByDiscipline,Days_Cared_For,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code,Other_Diagnosis_Code_1_ICD_10_C_M,Other_Diagnosis_Code_2_ICD_10_C_M,Other_Diagnosis_Code_3_ICD_10_C_M,Other_Diagnosis_Code_4_ICD_10_C_M,Other_Diagnosis_Code_5_ICD_10_C_M,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,BMI,BMI_Category,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV,ICD_Section,ICD_Range
0,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGUzeSUD9e,2017-06-20,1AFKS,9645,90,Female,0,0,0,0,0,1,RN,112,457640,I50.9,M19.90,I10.,E27.1,Q20.8,M17.9,0,1,0,1,0,28.081267,Overweight,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'I00-I99', 'M00-M99', 'Q00-Q99'}"
1,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGUe9ezeDN,2017-12-20,1CGPT,9645,82,Male,0,0,0,0,0,1,RN,0,457640,S72.001S,Z51.89,R53.1,I50.9,M19.90,I10.,0,1,1,0,0,43.066384,Obese-Class3,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'poison...","{'M00-M99', 'S00-T88', 'Z00-Z99', 'I00-I99', '..."
2,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGWGXU9DSW,2017-11-06,1BGKS,9645,63,Female,0,0,0,0,0,1,RN,0,457640,I50.9,J44.9,Z51.89,J18.0,I10.,E11.9,0,1,0,0,0,67.849376,Obese-Class3,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'Endocr...","{'J00-J99', 'I00-I99', 'Z00-Z99', 'E00-E89'}"
3,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGUDGzWXUU,2017-07-05,1AGPS,9645,85,Male,0,0,0,0,0,1,RN,41,457640,I25.10,I21.3,R53.1,Z51.89,T14.8,Z48.00,0,0,0,1,0,27.061851,Overweight,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'poison...","{'R00-R99', 'I00-I99', 'Z00-Z99', 'S00-T88'}"
4,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGU9WU9eX9z,2017-09-06,1CGPS,9645,68,Male,0,0,0,1,0,0,RN,0,457640,I63.9,G81.91,Z51.89,E10.9,I10.,NaN,0,0,0,0,0,30.782249,Obese-Class1,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the nervous system', 'Diseases o...","{'G00-G99', 'I00-I99', 'Z00-Z99', 'E00-E89'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221952,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGGWGe99NUe,2017-02-17,1CHKS,9626,87,Male,0,0,0,1,0,0,RN,47,457754,F03.90,I12.9,N18.3,M19.90,M25.562,N40.0,0,0,0,1,1,32.612544,Obese-Class1,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the circulatory system', 'Behavi...","{'I00-I99', 'M00-M99', 'N00-N99', 'F01-F99'}"
221953,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGNGNUeNGe9,2017-04-20,2AFKS,366724,63,Female,0,0,0,0,0,1,RN,55,677943,R07.81,M25.572,W01.190D,M06.9,I10.,F32.9,0,0,0,1,0,38.616943,Obese-Class2,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the circulatory system', 'Behavi...","{'M00-M99', 'F01-F99', 'V00-Y99', 'I00-I99', '..."
221954,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGUU9zDSzSS,2017-03-28,5AHKS,9644,68,Female,0,0,0,0,0,1,RN,127,459482,R41.3,F33.2,G20.,F41.3,R53.83,F99.,0,0,0,1,1,24.028320,Normal weight,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the nervous system', 'Behavioral...","{'F01-F99', 'G00-G99', 'R00-R99'}"
221955,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGXzG9G9Uze,2017-11-30,2BHMS,9644,71,Female,0,0,0,0,0,1,RN,0,459482,N39.0,M54.5,J44.9,F17.200,I12.9,N18.3,0,0,0,0,0,31.928783,Obese-Class1,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the circulatory system', 'Behavi...","{'M00-M99', 'F01-F99', 'N00-N99', 'I00-I99', '..."
221956,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGXzGzDzeNN,2017-06-03,1AFKT,366724,70,Female,0,0,0,0,0,1,RN,159,677943,N10.,B96.20,Z45.2,Z79.2,I10.,Z87.891,0,0,0,1,0,24.207989,Normal weight,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Certain infectious and parasitic diseases', ...","{'N00-N99', 'I00-I99', 'Z00-Z99', 'A00-B99'}"

In [5]:
full_cohort = df.copy()
diabetes_cohort = full_cohort[full_cohort['has_diabetes'] == 1]
hf_cohort = full_cohort[full_cohort['has_heart_failure'] == 1]
htn_cohort = full_cohort[full_cohort['has_hypertension'] == 1]

In [6]:
diabetes_cohort.to_csv('../cohorts/diabetes_v1.csv', index=False)
hf_cohort.to_csv('../cohorts/heartfailure_v1.csv', index=False)
htn_cohort.to_csv('../cohorts/hypertension_v1.csv', index=False)

In [7]:
diabetes_cohort

,County,Fips,geometry,Beneficiary_ID,Assessment_Effective_Date,Submitted_HIPPS_Code,Facility_Internal_ID,Age,Gender,American_Indian_or_Alaska_Native,Asian,Black_or_African_American,Hispanic_or_Latino,Native_Hawiian_or_Pacific_Islander,White,ByDiscipline,Days_Cared_For,Agency_Medicare_Number,Primary_Diagnosis_ICD_10_C_M_Code,Other_Diagnosis_Code_1_ICD_10_C_M,Other_Diagnosis_Code_2_ICD_10_C_M,Other_Diagnosis_Code_3_ICD_10_C_M,Other_Diagnosis_Code_4_ICD_10_C_M,Other_Diagnosis_Code_5_ICD_10_C_M,has_diabetes,has_heart_failure,has_hypertension,ever_deceased,ever_readmitted,BMI,BMI_Category,POP_URB,POPPCT_URB,POP_RUR,POPPCT_RUR,ACS_PCT_BACHELOR_DGR,ACS_PCT_COLLEGE_ASSOCIATE_DGR,ACS_PCT_GRADUATE_DGR,ACS_PCT_HS_GRADUATE,ACS_PCT_LT_HS,ACS_PCT_NO_WORK_NO_SCHL_16_19,ACS_PCT_POSTHS_ED,ACS_PCT_VET_BACHELOR,ACS_PCT_VET_COLLEGE,ACS_PCT_VET_HS,ACS_PCT_HH_LIMIT_ENGLISH,ACS_PCT_HH_BROADBAND,ACS_PCT_HH_BROADBAND_ONLY,ACS_PCT_HH_CELLULAR,ACS_PCT_HH_CELLULAR_ONLY,ACS_PCT_HH_DIAL_INTERNET_ONLY,ACS_PCT_HH_INTERNET,ACS_PCT_HH_INTERNET_NO_SUBS,ACS_PCT_HH_NO_COMP_DEV,ACS_PCT_HH_NO_INTERNET,ACS_PCT_HH_OTHER_COMP,ACS_PCT_HH_OTHER_COMP_ONLY,ACS_PCT_HH_PC,ACS_PCT_HH_PC_ONLY,ACS_PCT_HH_SAT_INTERNET,ACS_PCT_HH_SMARTPHONE,ACS_PCT_HH_SMARTPHONE_ONLY,ACS_PCT_HH_TABLET,ACS_PCT_HH_TABLET_ONLY,ACS_PCT_CHILDREN_GRANDPARENT,ACS_PCT_CHILD_1FAM,ACS_PCT_GRANDP_NO_RESPS,ACS_PCT_GRANDP_RESPS_NO_P,ACS_PCT_GRANDP_RESPS_P,ACS_PCT_HH_1PERS,ACS_PCT_HH_ABOVE65,ACS_PCT_HH_ALONE_ABOVE65,ACS_PCT_HH_KID_1PRNT,ACS_TOT_GRANDCHILDREN_GP,ACS_PCT_HEALTH_INC_138_199,ACS_PCT_HEALTH_INC_200_399,ACS_PCT_HEALTH_INC_ABOVE400,ACS_PCT_HEALTH_INC_BELOW137,ACS_PCT_HH_1FAM_FOOD_STMP,ACS_PCT_HH_FOOD_STMP_BLW_POV,ACS_PCT_HH_NO_FD_STMP_BLW_POV,ACS_PCT_HH_PUB_ASSIST,ACS_PCT_INC50,ACS_PCT_INC50_ABOVE65,ACS_PCT_NONVET_POV_18_64,ACS_PCT_PERSON_INC_100_124,ACS_PCT_PERSON_INC_125_199,ACS_PCT_PERSON_INC_ABOVE200,ACS_PCT_PERSON_INC_BELOW99,ACS_PCT_POV_AIAN,ACS_PCT_POV_ASIAN,ACS_PCT_POV_BLACK,ACS_PCT_POV_HISPANIC,ACS_PCT_POV_MULTI,ACS_PCT_POV_NHPI,ACS_PCT_POV_OTHER,ACS_PCT_POV_WHITE,ACS_PCT_VET_POV_18_64,ACS_TOT_POP_POV,ICD_Section,ICD_Range
8,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGSzeeDNNX,2017-01-06,3AHKS,9626,64,Female,0,0,0,0,0,1,RN,336,457754,E11.51,E11.43,I10.,F41.9,M19.90,F32.9,1,0,0,1,1,38.405307,Obese-Class2,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'I00-I99', 'M00-M99', 'F01-F99'}"
16,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGDeUSGeGS,2017-04-01,1CFPT,9645,72,Female,0,0,0,0,0,1,RN,25,457640,I50.9,L03.116,Z51.89,E11.9,I87.2,I27.2,1,1,0,1,0,35.989210,Obese-Class2,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'L00-L99', 'I00-I99', 'Z00-Z99'}"
20,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGGUzGD9zGU,2017-07-21,1AFKS,9645,93,Male,0,0,0,0,0,1,RN,20,457640,E11.9,I10.,H35.30,N40.0,R32.,F03.90,1,0,0,1,0,30.035400,Obese-Class1,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the eye and adnexa', 'Diseases o...","{'E00-E89', 'F01-F99', 'H00-H59', 'N00-N99', '..."
27,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGXzDWeUeXe,2017-01-24,1CFKW,9645,70,Female,0,0,0,1,0,0,RN,38,457640,C20.,E11.9,Z43.3,Z97.8,NaN,NaN,1,0,0,1,0,26.700832,Overweight,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Endocrine', 'Factors influencing health stat...","{'E00-E89', 'C00-D49', 'Z00-Z99'}"
31,Ochiltree,48357,"POLYGON ((-100.936058 36.499602, -100.918513 3...",GGGGGGU9WWeUDWG,2017-11-30,1BHPT,9645,64,Male,0,0,0,0,0,1,RN,0,457640,E11.8,Z51.89,N18.6,I10.,I27.20,I35.1,1,0,1,0,0,23.959388,Normal weight,8391.0,83.78,1624.0,16.22,15.910000,23.463333,3.603333,34.100000,22.926667,0.000,42.976667,17.953333,46.540000,35.506667,8.370,55.280000,8.616667,73.020000,19.376667,0.036667,82.113333,3.976667,7.206667,13.910000,2.193333,0.000000,77.963333,5.146667,13.303333,80.883333,6.773333,61.783333,1.290000,1.880000,19.400000,6.190000,16.190000,10.953333,24.010000,24.280000,8.576667,15.466667,23.333333,14.536667,31.543333,25.836667,28.086667,48.253333,4.780000,6.543333,12.360000,2.853333,1.640000,11.696667,10.650000,19.216667,57.376667,12.753333,0.000000,0.000,0.000000,11.973333,17.173333,0.000000,8.830000,7.813333,0.000000,3272.000000,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'I00-I99', 'Z00-Z99', 'N00-N99'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221922,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGUUeeUUGzW,2017-08-17,5BHKT,9644,68,Female,0,0,0,0,0,1,RN,117,459482,L89.610,E11.9,J44.9,H25.9,R41.82,I50.20,1,0,0,1,0,39.475098,Obese-Class2,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the eye and adnexa', 'Diseases o...","{'E00-E89', 'H00-H59', 'L00-L99', 'I00-I99', '..."
221923,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGXzGe9USU9,2017-04-19,2CGLW,63855,70,Male,0,0,0,0,0,1,RN,128,679259,E11.621,L97.812,L97.512,E11.22,I13.0,N18.4,1,0,1,1,0,39.528547,Obese-Class2,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'L00-L99', 'I00-I99', 'N00-N99'}"
221924,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGXzSeDzeeG,2017-01-14,2AGMS,9626,59,Female,0,0,0,0,0,1,RN,325,457754,M62.81,R41.82,M19.90,J44.9,E11.9,M54.5,1,0,0,1,0,31.115030,Obese-Class1,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Endocrine', 'nutritional and metabolic disea...","{'E00-E89', 'M00-M99', 'J00-J99', 'R00-R99'}"
221935,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGXzUeN9XXN,2017-03-24,1CHPT,366724,70,Male,0,0,0,0,0,1,RN,116,677943,I50.32,L03.115,L03.116,R53.1,E11.22,N18.4,1,1,0,1,1,36.885802,Obese-Class2,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'L00-L99', 'N00-N99', 'I00-I99', '..."
221942,Potter,48375,"POLYGON ((-101.622941 35.183117, -102.167471 3...",GGGGGGGWUz9D9WU,2017-10-25,1CHKS,366724,88,Female,0,0,0,0,0,1,RN,55,677943,D51.0,E11.42,I10.,I44.2,Z95.0,Z79.4,1,0,0,1,0,22.483643,Normal weight,105174.0,88.74,13351.0,11.26,10.271143,29.178571,4.688857,31.270571,21.734286,1.066,44.136000,16.220571,35.979714,44.943429,6.298,52.137143,6.893143,66.803714,19.718000,0.093143,75.282571,3.954000,9.720000,17.906857,1.649143,0.078571,59.698857,2.936571,5.867714,82.170286,22.107429,36.591143,0.626571,10.554286,35.555429,24.032857,31.221714,39.031429,30.947714,25.265429,11.048000,21.339714,95.971429,16.406571,29.270000,20.549714,30.917143,29.572857,8.009143,11.644857,15.646571,8.026000,5.324857,17.748286,8.417143,19.325429,49.791429,19.608571,12.897429,11.714,30.938286,21.613143,23.702000,11.428571,18.915429,18.542571,14.333429,3184.428571,"{'Diseases of the circulatory system', 'Endocr...","{'E00-E89', 'D50-D89', 'I00-I99', 'Z00-Z99'}"

In [8]:
diabetes_cohort.columns

Index(['County', 'Fips', 'geometry', 'Beneficiary_ID',
       'Assessment_Effective_Date', 'Submitted_HIPPS_Code',
       'Facility_Internal_ID', 'Age', 'Gender',
       'American_Indian_or_Alaska_Native',
       ...
       'ACS_PCT_POV_BLACK', 'ACS_PCT_POV_HISPANIC', 'ACS_PCT_POV_MULTI',
       'ACS_PCT_POV_NHPI', 'ACS_PCT_POV_OTHER', 'ACS_PCT_POV_WHITE',
       'ACS_PCT_VET_POV_18_64', 'ACS_TOT_POP_POV', 'ICD_Section', 'ICD_Range'],
      dtype='object', length=101)